parameters:
#    meta_admin.example.class: meta\AdminBundle\Example

services:
#    meta_admin.example:
#        class: %meta_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
