services:
    paypalHelper:
        class: meta\SubscriptionBundle\Services\PaypalHelper
        arguments: 
            sandbox: %paypal_sandbox%
            clientid: %paypal_clientid%
            secret: %paypal_secret%