parameters:
#    meta_user_profile.example.class: meta\UserProfileBundle\Example

services:
#    meta_user_profile.example:
#        class: %meta_user_profile.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
