parameters:
  launch:
    -
      name: Todo1
      description: Cette todo vous indique les étapes de la création d'entreprise
      items:
        - "Rédiger des status"
        - "Déposer les status"
        - "Récupérer un SIRET"
    -
      name: Todo2
      description: Cette todo vous indique les étapes de la création d'entreprise
      items:
        - "Rédiger des status"
        - "Déposer les status"
        - "Récupérer un SIRET"