parameters:
  standardproject.menu:
    timeline:
      icon: icon-comments-alt
      route: sp_show_project_timeline
      private: true
    info:
      icon: icon-info-sign
      route: sp_show_project
      private: false
    lists:
      icon: icon-tasks
      route: sp_show_project_list_home
      private: true
    resources:
      icon: icon-file
      route: sp_show_project_list_resources
      private: true
    wiki:
      icon: icon-font
      route: sp_show_project_wiki
      private: true