parameters:
  project.menu:
    timeline:
      icon: icon-comments-alt
      route: p_show_project_timeline
      private: false
    info:
      icon: icon-info-sign
      route: p_show_project
      private: false
    lists:
      icon: icon-tasks
      route: p_show_project_list_home
      private: false
    resources:
      icon: icon-file
      route: p_show_project_list_resources
      private: false
    wiki:
      icon: icon-font
      route: p_show_project_wiki
      private: false
