parameters:
  project.menu:
    timeline:
      icon: fa fa-comments
      route: p_show_project
      private: false
    info:
      icon: fa fa-info-circle
      route: p_show_project_info
      private: false
    lists:
      icon: fa fa-tasks
      route: p_show_project_list_home
      private: false
    resources:
      icon: fa fa-file
      route: p_show_project_list_resources
      private: false
    wiki:
      icon: fa fa-font
      route: p_show_project_wiki
      private: false
    settings:
      icon: fa fa-wrench
      route: p_show_project_settings
      private: true
