parameters:
  project.resource_types:
    pdf: 
      icon: file_extension_pdf
      displayable: true
    doc: 
      icon: file_extension_doc
      displayable: false
    docx: 
      icon: file_extension_doc
      displayable: false
    ppt: 
      icon: file_extension_ppt
      displayable: false
    pptx: 
      icon: file_extension_ppt
      displayable: false
    xls: 
      icon: file_extension_xls
      displayable: false
    xlsx: 
      icon: file_extension_xls
      displayable: false
    jpeg: 
      icon: file_extension_jpeg
      displayable: true
    jpg: 
      icon: file_extension_jpg
      displayable: true
    png: 
      icon: file_extension_png
      displayable: true
    gif: 
      icon: file_extension_gif
      displayable: true
    mp3:
      icon: file_extension_mp2
      displayable: true
    mpga:
      icon: file_extension_mpg
      displayable: true
    mp4:
      icon: file_extension_mp4
      displayable: true
    zip:
      icon: file_extension_zip
      displayable: false
    psd:
      icon: file_extension_psd
      displayable: false
    # Other providers types
    youtube_video:
      icon: file_extension_mswmm
      displayable: true
    gdocs_presentation:
      icon: gdocs_presentation
      displayable: true
    gdocs_folderview:
      icon: folders_explorer
      displayable: true
    gdocs_spreadsheet:
      icon: gdocs_spreadsheet
      displayable: true
    gdocs_document:
      icon: gdocs_document
      displayable: true
    gdocs_forms:
      icon: gdocs_forms
      displayable: true
    gdocs_#folders:
      icon: folders_explorer
      displayable: true
    gdocs_drawing:
      icon: gdocs_drawing
      displayable: true
    gdocs_file:
      icon: document_image_ver
      displayable: true
    prezi_prezi:
      icon: page
      displayable: true
    # Misc
    other: 
      icon: document_comments
      displayable: false
  project.resource_providers:
    gdocs:
      pattern: /(docs|drive)\.google\.com/
      icon: provider_gdocs
      downloadable: false
      types:
        type: regex
        value: "/\.google\.com\/(document|spreadsheet|folderview|presentation|file|forms|drawing|\#folders)/"
    evernote:
      pattern: /evernote\.com\/pub/
      icon: provider_evernote
      downloadable: false
    dropbox:
      pattern: /dropbox\.com/
      icon: provider_dropbox
      downloadable: false
      types:
        type: regex
        value: /\.([a-zA-Z]+)$/
    droplr:
      pattern: /d\.pr\/i/
      icon: provider_droplr
      downloadable: false
    youtube:
      pattern: /(youtube\.com|youtu\.be)/
      icon: provider_youtube
      downloadable: false
      types:
        type: fixed
        value: youtube_video
    prezi:
      pattern: /prezi\.com/
      icon: provider_prezi
      downloadable: false
      types:
        type: fixed
        value: prezi_prezi
    skydrive:
      pattern: /sdrv\.com/
      icon: provider_skydrive
      downloadable: false
    other:
      icon: provider_other
      downloadable: false
    local:
      icon: provider_local
      downloadable: true
    zapier:
      pattern: /zapier\.com/
      icon: provider_zapier
      downloadable: false
