parameters:
#    meta_project.example.class: meta\ProjectBundle\Example

services:
#    meta_project.example:
#        class: %meta_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
