<?php

namespace meta\IdeaProfileBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IdeaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdeaRepository extends EntityRepository
{

  public function findRecentlyCreatedIdeas($limit)
  {
    
    $qb = $this->getEntityManager()->createQueryBuilder();

    return $qb->select('i')
            ->from('metaIdeaProfileBundle:Idea', 'i')
            ->orderBy('i.created_at', 'DESC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();

  }

  public function findRecentlyUpdatedIdeas($limit)
  {
    
    $qb = $this->getEntityManager()->createQueryBuilder();

    return $qb->select('i')
            ->from('metaIdeaProfileBundle:Idea', 'i')
            ->orderBy('i.updated_at', 'DESC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
            
  }
}
