<?php

namespace meta\IdeaProfileBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IdeaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdeaRepository extends EntityRepository
{

  public function findRecentlyCreatedIdeas($limit, $onlyArchived)
  {
    
    $qb = $this->getEntityManager()->createQueryBuilder();

    return $qb->select('i')
            ->from('metaIdeaProfileBundle:Idea', 'i')
            ->where('i.archived = :bool')
            ->setParameter('bool', $onlyArchived)
            ->orderBy('i.created_at', 'DESC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();

  }

  public function findRecentlyUpdatedIdeas($limit)
  {
    
    $qb = $this->getEntityManager()->createQueryBuilder();

    return $qb->select('i')
            ->from('metaIdeaProfileBundle:Idea', 'i')
            ->where('i.archived = :bool')
            ->setParameter('bool', 0)
            ->orderBy('i.updated_at', 'DESC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
            
  }

  public function findTopIdeasForUser($userId, $max = 3)
  {
    
    $qb = $this->getEntityManager()->createQueryBuilder();

    return $qb->select('i')
            ->from('metaIdeaProfileBundle:Idea', 'i')
            ->join('i.creators', 'u')
            ->where('u.id = :userId')
            ->setParameter('userId', $userId)
            ->orderBy('i.updated_at', 'DESC')
            ->setMaxResults($max)
            ->getQuery()
            ->getResult();

  }

  public function computeWeekActivityForIdeas($ideas)
  {
 
    $qb = $this->getEntityManager()->createQueryBuilder();

    return $qb->select('l AS log')
            ->addSelect('i.id as id')
            ->addSelect('COUNT(DISTINCT l.id) AS nb_actions')
            ->addSelect('COUNT(DISTINCT c.id) AS nb_comments')
            ->addSelect('SUBSTRING(l.created_at,1,10) AS date')
            ->addSelect('MAX(l.created_at) AS last_activity')
            ->addSelect('u.username as username')

            ->from('metaGeneralBundle:Log\IdeaLogEntry', 'l')
            ->leftJoin('l.idea', 'i')
            
            ->leftJoin('i.logEntries', 'l2', 'WITH', 'SUBSTRING(l2.created_at,1,10) = SUBSTRING(l.created_at,1,10) AND l2.created_at > l.created_at')
            ->leftJoin('l2.user', 'u')
            ->leftJoin('i.comments', 'c', 'WITH', 'SUBSTRING(c.created_at,1,10) = SUBSTRING(l.created_at,1,10)')

            ->andWhere('i IN (:iids)')
            ->setParameter('iids', $ideas)
            ->andWhere("l.created_at > DATE_SUB(CURRENT_DATE(),7,'DAY')")
            
            ->groupBy('i.id, date')
            ->orderBy('i.updated_at', 'DESC')
            ->addOrderBy('date','DESC')
            ->getQuery()
            ->getResult();

  }
}
