<?php

namespace meta\StandardProjectProfileBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StandardProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StandardProjectRepository extends EntityRepository
{

  public function countProjects()
  {
    
    $qb = $this->getEntityManager()->createQueryBuilder();

    return $qb->select('COUNT(sp)')
            ->from('metaStandardProjectProfileBundle:StandardProject', 'sp')
            ->where('sp.deleted_at IS NULL')
            ->getQuery()
            ->getSingleScalarResult();

  }

  public function findStandardProjects($page, $maxPerPage, $sort)
  {
    
    $qb = $this->getEntityManager()->createQueryBuilder();
    $query = $qb->select('sp')
            ->from('metaStandardProjectProfileBundle:StandardProject', 'sp')
            ->where('sp.deleted_at IS NULL');

    switch ($sort) {
      case 'newest':
        $query->orderBy('sp.created_at', 'DESC');
        break;
      case 'alpha':
        $query->orderBy('sp.name', 'ASC');
        break;
      case 'update':
        $query->orderBy('sp.updated_at', 'DESC');
      default:
        break;
    }

    return $query->setFirstResult(($page-1)*$maxPerPage)
            ->setMaxResults($maxPerPage)
            ->getQuery()
            ->getResult();

  }


  public function findTopProjectsForUser($userId, $max = 3)
  {
    
    $qb = $this->getEntityManager()->createQueryBuilder();

    return $qb->select('sp, MAX(l.created_at) AS last_update')
            ->from('metaStandardProjectProfileBundle:StandardProject', 'sp')
            ->join('sp.logEntries', 'l')
            ->join('sp.owners', 'u')
            ->where('u.id = :userId')
            ->setParameter('userId', $userId)
            ->andWhere('sp.deleted_at IS NULL')
            ->groupBy('sp.id')
            ->orderBy('last_update', 'DESC')
            ->setMaxResults($max)
            ->getQuery()
            ->getResult();

  }

  public function computeWeekActivityForProjects($projects)
  {
 
    $qb = $this->getEntityManager()->createQueryBuilder();

    return $qb->select('l AS log')
            ->addSelect('sp.id as id')
            ->addSelect('COUNT(DISTINCT l.id) - COUNT(DISTINCT c.id) AS nb_actions')
            ->addSelect('COUNT(DISTINCT c.id) AS nb_comments')
            ->addSelect('SUBSTRING(l.created_at,1,10) AS date')
            ->addSelect('MAX(l.created_at) AS last_activity')

            ->from('metaGeneralBundle:Log\StandardProjectLogEntry', 'l')
            ->leftJoin('l.standardProject', 'sp')
            
            ->leftJoin('sp.logEntries', 'l2', 'WITH', 'SUBSTRING(l2.created_at,1,10) = SUBSTRING(l.created_at,1,10) AND l2.created_at > l.created_at')
            ->leftJoin('sp.comments', 'c', 'WITH', 'SUBSTRING(c.created_at,1,10) = SUBSTRING(l.created_at,1,10)')

            ->andWhere('sp IN (:pids)')
            ->setParameter('pids', $projects)
            ->andWhere("l.created_at > DATE_SUB(CURRENT_DATE(),7,'DAY')")
            
            ->andWhere('sp.deleted_at IS NULL')
            
            ->groupBy('sp.id, date')
            ->orderBy('sp.updated_at', 'DESC')
            ->addOrderBy('date','DESC')
            ->getQuery()
            ->getResult();

  }
}
