<?php

namespace meta\StandardProjectProfileBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StandardProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StandardProjectRepository extends EntityRepository
{

  public function findRecentlyCreatedStandardProjects($limit)
  {
    
    $qb = $this->getEntityManager()->createQueryBuilder();

    return $qb->select('sp')
            ->from('metaStandardProjectProfileBundle:StandardProject', 'sp')
            ->orderBy('sp.created_at', 'DESC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();

  }

  public function findRecentlyUpdatedStandardProjects($limit)
  {
    
    $qb = $this->getEntityManager()->createQueryBuilder();

    return $qb->select('sp')
            ->from('metaStandardProjectProfileBundle:StandardProject', 'sp')
            ->orderBy('sp.updated_at', 'DESC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
            
  }
}
