parameters:
#    meta_user.example.class: meta\UserBundle\Example

services:
#    meta_user.example:
#        class: %meta_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
