parameters:
#    meta_idea.example.class: meta\IdeaBundle\Example

services:
#    meta_idea.example:
#        class: %meta_idea.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
