home:
    path:  /
    defaults: { _controller: metaStaticBundle:Default:home}

contact:
    path:  /contact
    defaults: { _controller: metaStaticBundle:Default:contact}

terms:
    path:  /terms
    defaults: { _controller: metaStaticBundle:Default:terms}
