home:
    pattern:  /
    defaults: { _controller: metaStaticBundle:Default:home}

contact:
    pattern:  /contact
    defaults: { _controller: metaStaticBundle:Default:contact}

terms:
    pattern:  /terms
    defaults: { _controller: metaStaticBundle:Default:terms}
